require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - cnes.gemspec
   
Style/AccessorGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: 'exception'

Naming/PredicateName:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

RSpec:
  Exclude:
    - 'spec/factories/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

# while that is a good rule, AR objects can't be properly instance_double'd
RSpec/VerifiedDoubles:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'docker/**/*'
    - 'doc/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'vendor/**/*'
