name: Ruby

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '*'

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: RSpec ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.4'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0.4'
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Runs rubocop
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
